# [MANAGER]: Manager Deployment Configurations
controllerManager:
  replicas: 1
  container:
    image: controller:latest
    args:
      - "--leader-elect"
      - "--metrics-bind-address=:8080"
      - "--health-probe-bind-address=:8081"
    env:
      IMAGE_REGISTRY_PROXY: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-controller:main
      IMAGE_CONNECTION: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-connection:main
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /readyz
        port: 8081
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10
  serviceAccountName: registry-proxy-operator

# [RBAC]: To enable RBAC (Permissions) configurations
rbac:
  enable: true

# [METRICS]: Set to true to generate manifests for exporting metrics.
# To disable metrics export set false, and ensure that the
# ControllerManager argument "--metrics-bind-address=:8080" is removed.
metrics:
  enable: true
  port: 8080

# [NETWORK POLICIES]: To enable NetworkPolicies set true
networkPolicy:
  enable: false

# [Busola]: To enable Busola UI extension set true
busola:
  enable: true

namespace: 
  name: registry-proxy
  create: true