//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package connectivityproxy

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxy) DeepCopyInto(out *ConnectivityProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxy.
func (in *ConnectivityProxy) DeepCopy() *ConnectivityProxy {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectivityProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxyConfig) DeepCopyInto(out *ConnectivityProxyConfig) {
	*out = *in
	out.Servers = in.Servers
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxyConfig.
func (in *ConnectivityProxyConfig) DeepCopy() *ConnectivityProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxyHttp) DeepCopyInto(out *ConnectivityProxyHttp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxyHttp.
func (in *ConnectivityProxyHttp) DeepCopy() *ConnectivityProxyHttp {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxyHttp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxyList) DeepCopyInto(out *ConnectivityProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectivityProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxyList.
func (in *ConnectivityProxyList) DeepCopy() *ConnectivityProxyList {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectivityProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxyServerProxy) DeepCopyInto(out *ConnectivityProxyServerProxy) {
	*out = *in
	out.Http = in.Http
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxyServerProxy.
func (in *ConnectivityProxyServerProxy) DeepCopy() *ConnectivityProxyServerProxy {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxyServerProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxyServers) DeepCopyInto(out *ConnectivityProxyServers) {
	*out = *in
	out.Proxy = in.Proxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxyServers.
func (in *ConnectivityProxyServers) DeepCopy() *ConnectivityProxyServers {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxyServers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityProxySpec) DeepCopyInto(out *ConnectivityProxySpec) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityProxySpec.
func (in *ConnectivityProxySpec) DeepCopy() *ConnectivityProxySpec {
	if in == nil {
		return nil
	}
	out := new(ConnectivityProxySpec)
	in.DeepCopyInto(out)
	return out
}
