module-name: registry-proxy
# rc-tag: 0.0.0
kind: kyma
mend:
  language: golang-mod
  exclude:
    - "**/tests/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/tests/**"
    - "**/*_test.go"
