{{- if .Values.rbac.enable }}
# permissions for end users to edit connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: kyma-connection-edit
rules:
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - connections
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - connections/status
    verbs:
      - get
{{- end -}}
