#!/bin/bash
echo "Running make generate manifests..."
make generate manifests

if [[ -n $(git status --porcelain) ]]; then
  echo "Autogenerated files updated. Adding them to the commit."
  git add .
fi