#!/bin/bash
echo "Running make generate manifests..."
cd "$(git rev-parse --show-toplevel)" || exit 1
make generate manifests

if [[ -n $(git status --porcelain) ]]; then
  echo "Autogenerated files updated. Adding them to the commit."
  git add config/

  find . -path "*/**/zz_generated.deepcopy.go" -exec git add {} +
fi