name: create release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name ( e.g. "2.1.3" )'
        default: ""
        required: true
      latest_release:
        description: "Latest release"
        type: boolean
        default: false

permissions: # used by build images steps
  id-token: write # This is required for requesting the JWT token
  contents: write # This is required for actions/checkout

jobs:
  upgrade-images:
    name: Upgrade main images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0

      - name: Bump helm chart
        run: |
          ./.github/scripts/upgrade-rp-version.sh
        env:
          MODULE_VERSION: ${{ github.event.inputs.name }}

      - name: Bump sec-scanners-config.yaml
        run: ./.github/scripts/upgrade-sec-scanners-config.sh
        env:
          IMG_VERSION: ${{ github.event.inputs.name }}

      - name: Commit&Push
        run: |
          git config --local user.email "otter-releaser@otter-releaser.noreply.github.com"
          git config --local user.name "otter-releaser"

          git add .
          git commit --allow-empty -m "upgrade dependencies"
          git push origin ${{ github.ref_name }}

  create-tag:
    name: Create tag
    needs: upgrade-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref_name }} # Checkout to latest branch changes

      - name: Tag latest
        if: ${{ github.event.inputs.latest_release }}
        # tag commit to inform another workload, responsible for creating right release
        # that this release should be the latest one
        run: |
          git tag --force latest
          git push  --force origin latest

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.name }}
          git push origin ${{ github.event.inputs.name }}
